name: CI

on: pull_request

jobs:
  e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - name: Build / Test
        run: bun run build
      
      ### Just Files
      - name: Just Files
        id: just-files
        continue-on-error: true
        uses: ./
        with:
          baseUrl: 'https://hashicorp.com'
          files: 'pages/test.mdx'
        
      - name: Assert Just Files
        run: |
          expected='[{"path":"pages/1/2/3/4/test.mdx","start_line":3,"end_line":3,"start_column":42,"end_column":74,"annotation_level":"failure","message":"https://hashicorp.com/broken/link :: Error code 404"},{"path":"pages/1/2/file.mdx","start_line":3,"end_line":3,"start_column":1,"end_column":55,"annotation_level":"failure","message":"https://www.google.com/broken/link :: Error code 404"},{"path":"pages/test.mdx","start_line":3,"end_line":3,"start_column":42,"end_column":74,"annotation_level":"failure","message":"https://hashicorp.com/broken/link :: Error code 404"}]'
          actual=$(echo "${{ toJson(steps.just-files.outputs.annotations) }}")
          if [ "$expected" != "$actual" ]; then
            echo "Expected: $expected"
            echo "Actual: $actual"
            exit 1
          fi

      ### Just Directory
      - name: Just Directory
        id: just-directory
        continue-on-error: true
        uses: ./
        with:
          baseUrl: 'https://hashicorp.com'
          directory: "pages"

      - name: Assert Just Directory
        run: |
          expected='[{"path":"pages/1/2/3/4/test.mdx","start_line":3,"end_line":3,"start_column":42,"end_column":74,"annotation_level":"failure","message":"https://hashicorp.com/broken/link :: Error code 404"}]'
          actual=$(echo "${{ toJson(steps.just-directory.outputs.annotations) }}")
          if [ "$expected" != "$actual" ]; then
            echo "Expected: $expected"
            echo "Actual: $actual"
            exit 1
          fi

      ### Files and Directory
      - name: Files and Directory
        id: files-and-directory
        continue-on-error: true
        uses: ./
        with:
          baseUrl: 'https://hashicorp.com'
          files: 'pages/test.mdx'
          directory: "pages/1/2"
      
      - name: Assert Output
        run: |
          expected='[{"path":"pages/test.mdx","start_line":3,"end_line":3,"start_column":42,"end_column":74,"annotation_level":"failure","message":"https://hashicorp.com/broken/link :: Error code 404"},{"path":"pages/1/2/3/4/test.mdx","start_line":3,"end_line":3,"start_column":42,"end_column":74,"annotation_level":"failure","message":"https://hashicorp.com/broken/link :: Error code 404"}]'
          actual=$(echo "${{ toJson(steps.files-and-directory.outputs.annotations) }}")
          if [ "$expected" != "$actual" ]; then
            echo "Expected: $expected"
            echo "Actual: $actual"
            exit 1
          fi

  test:
    name: Typecheck / Lint / Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - name: Typecheck
        run: bun run tsc

      - name: Lint
        run: bun run check

      - name: Unit Test
        run: bun run test
