name: Publish

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: oven-sh/setup-bun@v1

      - run: bun i
      - run: bun run build

      # Create your semantically version release
      - uses: teunmooij/github-versioned-release@v1
        with:
          template: 'javascript-action'
        env:
          GITHUB_TOKEN: ${{ github.token }}
