name: 'C/I'

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  ci:
    name: Build / Test / Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: bun install

      - name: Build / Test
        run: bun run all

      - name: Run
        id: action
        continue-on-error: true
        uses: ./
        with:
          baseUrl: 'https://hashicorp.com'
          files: 'pages/test.mdx'

      - run: |
          echo ${{ toJson(steps.action.outputs.annotations) }}
